"""empty message

Revision ID: 22dd14482eef
Revises: 75ee1719bac7
Create Date: 2020-08-11 08:20:27.993638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22dd14482eef'
down_revision = '75ee1719bac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentor_profile', sa.Column('why', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentor_profile', 'why')
    # ### end Alembic commands ###
