"""empty message

Revision ID: 368482e8d28b
Revises: 22dd14482eef
Create Date: 2020-08-12 12:26:32.648277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368482e8d28b'
down_revision = '22dd14482eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('check_in_sent', sa.Boolean(), nullable=True))
    op.add_column('appointment', sa.Column('follow_up_sent', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('invite_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'invite_sent')
    op.drop_column('appointment', 'follow_up_sent')
    op.drop_column('appointment', 'check_in_sent')
    # ### end Alembic commands ###
