"""empty message

Revision ID: 443196261b1d
Revises: d90bf7b5d206
Create Date: 2020-07-21 09:39:05.361662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443196261b1d'
down_revision = 'd90bf7b5d206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('recorded', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('recorded_link', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'recorded_link')
    op.drop_column('event', 'recorded')
    # ### end Alembic commands ###
