"""empty message

Revision ID: 75ee1719bac7
Revises: 274863b30df2
Create Date: 2020-08-10 14:17:47.325899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ee1719bac7'
down_revision = '274863b30df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentor_profile', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentor_profile', 'status')
    # ### end Alembic commands ###
