"""empty message

Revision ID: 8c764420af69
Revises: caae595ff85a
Create Date: 2020-07-27 14:04:50.017914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c764420af69'
down_revision = 'caae595ff85a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_email', sa.Column('prefix', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_email', 'prefix')
    # ### end Alembic commands ###
