"""empty message

Revision ID: 9a268d5aa3a4
Revises: 03802ed8b5c2
Create Date: 2020-07-31 17:55:14.466211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a268d5aa3a4'
down_revision = '03802ed8b5c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('link', sa.String(length=1000), nullable=True),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_article')
    # ### end Alembic commands ###
