"""empty message

Revision ID: a8cb483462c9
Revises: 23dac119f760
Create Date: 2020-07-29 18:34:39.055943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8cb483462c9'
down_revision = '23dac119f760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('zoom_password', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'zoom_password')
    # ### end Alembic commands ###
