"""empty message

Revision ID: bb74f39985f7
Revises: f91d07dafdec
Create Date: 2020-08-10 09:46:33.562454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb74f39985f7'
down_revision = 'f91d07dafdec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment', 'zoom_password')
    op.drop_column('appointment', 'zoom_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('zoom_link', mysql.VARCHAR(collation='utf8_unicode_ci', length=1000), nullable=True))
    op.add_column('appointment', sa.Column('zoom_password', mysql.VARCHAR(collation='utf8_unicode_ci', length=1000), nullable=True))
    # ### end Alembic commands ###
