"""empty message

Revision ID: caae595ff85a
Revises: c49fea028931
Create Date: 2020-07-27 11:57:35.602140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caae595ff85a'
down_revision = 'c49fea028931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=10000), nullable=True),
    sa.Column('button_text', sa.String(length=100), nullable=True),
    sa.Column('button_link', sa.String(length=1000), nullable=True),
    sa.Column('header_text', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=1000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('audience', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_email')
    # ### end Alembic commands ###
