"""empty message

Revision ID: ea0a73814211
Revises: 443196261b1d
Create Date: 2020-07-21 09:39:42.204657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea0a73814211'
down_revision = '443196261b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speaker_profile', sa.Column('email', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('speaker_profile', 'email')
    # ### end Alembic commands ###
